// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD0LpMB3MAXe9aznfdsVOvHL_x1wtVmiU',
    appId: '1:247604125728:android:4332e074dd090c88b49c45',
    messagingSenderId: '247604125728',
    projectId: 'chat-app-88cfe',
    storageBucket: 'chat-app-88cfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKXxeIAQNoIedTorzpKY92yIFcCC7vOj0',
    appId: '1:247604125728:ios:c07d44e2f31e2bdcb49c45',
    messagingSenderId: '247604125728',
    projectId: 'chat-app-88cfe',
    storageBucket: 'chat-app-88cfe.firebasestorage.app',
    androidClientId:
        '247604125728-t3t9ihn88kvokcj5ni4mltanfklg0gmt.apps.googleusercontent.com',
    iosClientId:
        '247604125728-uojn8768s3etb9uuj7t1ipru1htd8atm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
